eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
    instance:
      hostname: localhost
      
user:
  application:
    name: Hi I am from User application(application.yml from GIT). WELCOME
